[2024-05-13T23:31:41.147+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ademe_transform_data.transform_data_task manual__2024-05-13T23:31:38.465111+00:00 [queued]>
[2024-05-13T23:31:41.194+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ademe_transform_data.transform_data_task manual__2024-05-13T23:31:38.465111+00:00 [queued]>
[2024-05-13T23:31:41.195+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-05-13T23:31:41.473+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): transform_data_task> on 2024-05-13 23:31:38.465111+00:00
[2024-05-13T23:31:41.503+0000] {standard_task_runner.py:60} INFO - Started process 29936 to run task
[2024-05-13T23:31:41.523+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ademe_transform_data', 'transform_data_task', 'manual__2024-05-13T23:31:38.465111+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/transform.py', '--cfg-path', '/tmp/tmp_epj1ctw']
[2024-05-13T23:31:41.528+0000] {standard_task_runner.py:88} INFO - Job 172: Subtask transform_data_task
[2024-05-13T23:31:41.728+0000] {task_command.py:423} INFO - Running <TaskInstance: ademe_transform_data.transform_data_task manual__2024-05-13T23:31:38.465111+00:00 [running]> on host 86724742ac03
[2024-05-13T23:31:42.132+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ademe_transform_data' AIRFLOW_CTX_TASK_ID='transform_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-13T23:31:38.465111+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-13T23:31:38.465111+00:00'
[2024-05-13T23:31:42.437+0000] {logging_mixin.py:188} INFO -            n_dpe                                            payload
0  2185N0146647X  {"conso_chauffage_depensier_e_finale": "917.6"...
1  2144N0042508Z  {"conso_chauffage_depensier_e_finale": "1651.8...
2  2156N0269293Y  {"conso_chauffage_depensier_e_finale": "1280.2...
3  2150N0042791C  {"conso_chauffage_depensier_e_finale": "2060.2...
4  2138N0565214V  {"conso_chauffage_depensier_e_finale": "2042.5...
[2024-05-13T23:31:42.438+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/transform.py", line 53, in transform
    new_row[col] = payload[col]
TypeError: string indices must be integers
[2024-05-13T23:31:42.529+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=ademe_transform_data, task_id=transform_data_task, execution_date=20240513T233138, start_date=20240513T233141, end_date=20240513T233142
[2024-05-13T23:31:42.601+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 172 for task transform_data_task (string indices must be integers; 29936)
[2024-05-13T23:31:42.658+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-13T23:31:42.799+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
